### ISSUE TITLE
Enhance documentation - graphviz must be installed

### ISSUE THREAD

**Issue by de-posthac** [sbarzaghialteaup/mta-visual-dep#7]
The documentation requires a note that graphviz ([graphviz.org](https://graphviz.org)) must be installed. On MacOS you can install the direct with `brew install graphviz.`

**Comment by sbarzaghialteaup** [comment]
Hi, 

Documentation now contains a note that graphviz is a requirement and a link to the download page of graphviz.
Thank you for your suggestion!

Ciao
Sam
